vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.5:9Wg0Glx/TwD8ElFBg+FKcQ==
    - esbenp.prettier-vscode@4.5.0:fguxa9vi0SKDxoBK+kx0eg==

tasks:
  - init: yarn && yarn build
  - command: cd mobile/ && yarn tunnel
  - command: cd backend/ && yarn dev
  - command: cd frontend/ && yarn start
  - command: yarn && yarn global commitizen
